"""
Report Generator Component
Implements generatePDFReport() from SDD Section 5.5 using ReportLab.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

DATA_DIR = os.environ.get("DATA_DIR", os.path.join(os.path.dirname(__file__), ".."))
EXPORT_DIR = os.path.join(DATA_DIR, "exports")
os.makedirs(EXPORT_DIR, exist_ok=True)


def generate_pdf_report(trend, sentiment, growth_rate, virality_score, stage, user_email):
    """
    Builds a standardized PDF report (title, timestamp, date range, charts-as-tables)
    matching SDD Section 3.8.1's report format requirement.
    """
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#1a1a2e"))

    filename = f"trend_{trend['keyword'].replace(' ', '_')}_{trend['platform']}_{int(datetime.utcnow().timestamp())}.pdf"
    file_path = os.path.join(EXPORT_DIR, filename)

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    elements = []

    elements.append(Paragraph(f"Trend Analysis Report: {trend['keyword']}", title_style))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph(f"Generated by: {user_email}", styles["Normal"]))
    elements.append(Paragraph(f"Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", styles["Normal"]))
    elements.append(Paragraph(f"Platform: {trend['platform']}", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    summary_data = [
        ["Metric", "Value"],
        ["Total Views", f"{trend['total_views']:,}"],
        ["Growth Rate", f"{growth_rate}%"],
        ["Virality Index", f"{virality_score}/100"],
        ["Trend Stage", stage],
    ]
    summary_table = Table(summary_data, colWidths=[8 * cm, 8 * cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4361ee")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.6 * cm))

    elements.append(Paragraph("Sentiment Breakdown", styles["Heading2"]))
    sentiment_data = [
        ["Sentiment", "Percentage"],
        ["Positive", f"{sentiment['positive_score']}%"],
        ["Negative", f"{sentiment['negative_score']}%"],
        ["Neutral", f"{sentiment['neutral_score']}%"],
        ["Dominant Sentiment", sentiment["dominant_sentiment"].capitalize()],
    ]
    sentiment_table = Table(sentiment_data, colWidths=[8 * cm, 8 * cm])
    sentiment_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f72585")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    elements.append(sentiment_table)

    doc.build(elements)
    return filename, file_path
