"""
Report Generator Component
Implements generatePDFReport() from SDD Section 5.5 using ReportLab.
"""

import io
import os
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

DATA_DIR = os.environ.get("DATA_DIR", os.path.join(os.path.dirname(__file__), ".."))
EXPORT_DIR = os.path.join(DATA_DIR, "exports")
try:
    os.makedirs(EXPORT_DIR, exist_ok=True)
except Exception:
    pass


def _build_pdf_elements(trend, sentiment, growth_rate, virality_score, stage, user_email):
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#1a1a2e"))

    elements = []
    elements.append(Paragraph(f"Trend Analysis Report: {trend['keyword']}", title_style))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph(f"Generated by: {user_email}", styles["Normal"]))
    elements.append(Paragraph(f"Generated on: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", styles["Normal"]))
    elements.append(Paragraph(f"Platform: {trend['platform']}", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    summary_data = [
        ["Metric", "Value"],
        ["Total Views", f"{trend['total_views']:,}"],
        ["Growth Rate", f"{growth_rate}%"],
        ["Virality Index", f"{virality_score}/100"],
        ["Trend Stage", stage],
    ]
    summary_table = Table(summary_data, colWidths=[8 * cm, 8 * cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4361ee")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.6 * cm))

    elements.append(Paragraph("Sentiment Breakdown", styles["Heading2"]))
    sentiment_data = [
        ["Sentiment", "Percentage"],
        ["Positive", f"{sentiment['positive_score']}%"],
        ["Negative", f"{sentiment['negative_score']}%"],
        ["Neutral", f"{sentiment['neutral_score']}%"],
        ["Dominant Sentiment", sentiment["dominant_sentiment"].capitalize()],
    ]
    sentiment_table = Table(sentiment_data, colWidths=[8 * cm, 8 * cm])
    sentiment_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f72585")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    elements.append(sentiment_table)
    return elements


def generate_pdf_report_buffer(trend, sentiment, growth_rate, virality_score, stage, user_email):
    """
    Builds a standardized PDF report into an in-memory BytesIO buffer.
    Immune to read-only filesystems and serverless runtime constraints.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    elements = _build_pdf_elements(trend, sentiment, growth_rate, virality_score, stage, user_email)
    doc.build(elements)
    buffer.seek(0)
    filename = f"trend_{trend['keyword'].replace(' ', '_')}_{trend['platform']}_{int(datetime.now(timezone.utc).timestamp())}.pdf"
    return filename, buffer


def generate_pdf_report(trend, sentiment, growth_rate, virality_score, stage, user_email):
    """
    Builds a standardized PDF report to disk (for backwards compatibility).
    """
    filename, buffer = generate_pdf_report_buffer(trend, sentiment, growth_rate, virality_score, stage, user_email)
    try:
        os.makedirs(EXPORT_DIR, exist_ok=True)
        file_path = os.path.join(EXPORT_DIR, filename)
        with open(file_path, "wb") as f:
            f.write(buffer.getvalue())
        return filename, file_path
    except Exception:
        return filename, ""
